class LocalizationData {
  static const Map<String, Map<String, String>> data = {
    'en': {
      'appName': 'Quick Save',
      'success': 'Success',
      'error': 'Error',
      'ok': 'OK',
      'cancel': 'Cancel',
      'loading': 'Loading...',
      'downloadTitle': 'Download Video & Audio',
      'downloadSubtitle': 'Paste any link and save it instantly',
      'pasteUrlHint': 'Paste URL here...',
      'pasteLinkBtn': 'Paste Link',
      'clearTextBtn': 'Clear Text',
      'downloadBtn': 'Download',
      'downloaderBtn': 'Downloader',
      'platforms': 'Platforms',
      'mediaTools': 'Media Tools',
      'seeAll': 'See All',
      'mediaToolsSubtitle': 'Edit video or audio already saved on your device.',
      'instagram': 'Instagram',
      'facebook': 'Facebook',
      'tiktok': 'TikTok',
      'youtube': 'YouTube',
      'other': 'Other',
      'removeWatermark': 'Magic Eraser',
      'removeWatermarkDesc': 'Erase unwanted objects from videos & images',
      'addWatermark': 'Add Watermark',
      'addWatermarkDesc': 'Add your own logo or text to your videos',
      'trimVideo': 'Trim Video',
      'trimVideoDesc': 'Cut specific parts of your video',
      'convertFormat': 'Convert Format',
      'convertFormatDesc': 'Change video or audio file type',
      'compress': 'Compress',
      'compressDesc': 'Reduce video or audio file size',
      'removeAudio': 'Remove Audio',
      'removeAudioDesc': 'Export video without sound',
      'muteVideo': 'Mute Video',
      'muteVideoDesc': 'Remove sound from video',
      'extractMp3': 'Extract MP3',
      'extractMp3Desc': 'Get audio from any video file',
      'chooseSource': 'Choose a source',
      'pickSourceDesc': 'Pick a video from your gallery or paste a link.',
      'uploadFromGallery': 'Upload from Gallery',
      'failedToLoadVideo': 'Failed to load video',
      'or': 'OR',
      'downloading': 'Downloading',
      'processing': 'Processing',
      'loadFromUrl': 'Load from URL',
      'generatingPreview': 'Generating Preview...',
      'startTimeLabel': 'START TIME (MM:SS)',
      'endTimeLabel': 'END TIME (MM:SS)',
      'customTimer': 'Custom Timer',
      'slider': 'Slider',
      'trimmingFailed': 'Trimming failed',
      'saveTrimmedVideo': 'SAVE TRIMMED VIDEO',
      'trimmedSavedSuccess': 'Trimmed video saved to gallery!',
      'pasteLinkFirst': 'Paste a link first',
      'invalidLink': 'Invalid Link',
      'couldNotReadLink': 'Could not read this link',
      'checkLinkRetry': 'Please check the link and try again.',
      'copyVideoLinkFrom': 'Copy a video link from',
      'galleryAccessFailed': 'Gallery access failed',
      'settings': 'Settings',
      'preferences': 'Preferences',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'theme': 'Theme',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'systemDefault': 'System Default',
      'support': 'Support',
      'faq': 'FAQ',
      'faqDesc': 'Frequently Asked Questions',
      'legal': 'Legal',
      'terms': 'Terms & Conditions',
      'termsDesc': 'Rules for using Quick Save',
      'privacy': 'Privacy Policy',
      'privacyDesc': 'How we handle your data',
      'selectFormat': 'Select Format',
      'video': 'Video',
      'videoQuality': 'Video Quality',
      'audio': 'Audio',
      'audioQuality': 'Audio Quality',
      'saved': 'Saved!',
      'viewHistory': 'View History',
      'downloadStarted': 'Download started',
      'downloadFailed': 'Download failed',
      'highQualityMP3': 'High Quality · MP3',
      'audioOnly': 'Audio Only',
      'chooseAQualityFirst': 'Choose a quality first',
      'yourFileHasBeenSavedToYourDevice': 'Your file has been saved to your device.',
      'history': 'History',
      'mp3': 'MP3',
      'clearHistory': 'Clear History',
      'noHistory': 'No downloads yet',
      'tagDownload': 'Downloaded',
      'tagTrim': 'Trimmed',
      'tagConvert': 'Converted',
      'tagEraser': 'Erased',
      'tagWatermarked': 'Watermarked',
      'pleasePasteAValid': 'Please paste a valid',
      'link': 'link',
      'paste': 'Paste',
      'your': 'your',
      'linkHere': 'link here...',
      'linkBelowToStart': 'link below to start.',
      'convertFormatTitle': 'Convert Format',
      'chooseMediaType': 'Choose Media Type',
      'selectTargetFormat': 'Select Target Format',
      'pickAudioFile': 'Pick Audio File',
      'pickVideoFile': 'Pick Video File',
      'convertNow': 'Convert Now',
      'converting': 'Converting...',
      'conversionSuccess': 'File converted successfully!',
      'conversionFailed': 'Conversion failed. Please try again.',
      'noFileSelected': 'Please select a file first',
      'splashSubtitle': 'DOWNLOAD • EDIT • SHARE',
      'languageName': 'English',
      'chooseMedia': 'Choose Media',
      'chooseAudio': 'Choose Audio',
      'chooseVideo': 'Choose Video',
      'selectAndContinue': 'SELECT & CONTINUE',
      'position': 'Position',
      'size': 'Size',
      'magicEraser': 'Magic Eraser',
      'drawToErase': 'Draw to Erase',
      'simplyDraw': 'Simply draw a box over the watermark using your finger.',
      'generateVideo': 'GENERATE VIDEO',
      'clearSelection': 'Clear Selection',
      'changeVideo': 'Change Video',
      'addBranding': 'Add Branding',
      'dragBrand': 'Drag your brand anywhere on the video.',
      'typeWatermark': 'Type watermark...',
      'loadingMedia': 'Loading Media...',
      'watermarkBlur': 'Watermark Blur',
      'readyToErase': 'Ready to erase!',
      'eraseSelectedArea': 'ERASE SELECTED AREA',
      'openGallery': 'OPEN GALLERY',
      'posBlurBox': 'Position the Blur Box',
      'faqQ1': 'How to download a video?',
      'faqA1': 'Copy the video link from any supported platform, paste it in the home screen, and click continue.',
      'faqQ2': 'How to use Magic Eraser?',
      'faqA2': 'Upload an image or video, draw a box over the watermark or unwanted element, and click "Erase Selected Area".',
      'faqQ3': 'How to trim a video?',
      'faqA3': 'Go to Media Tools, select Trim Video, upload your video, and use the slider or custom timer to select the part you want to keep.',
      'faqQ4': 'How to convert file formats?',
      'faqA4': 'Select "Convert Format" from Media Tools, choose between Audio or Video, pick your file, and select the target format like MP3 or MP4.',
      'faqQ8': 'How to add a watermark to my video?',
      'faqA8': 'Go to Media Tools > Add Watermark, select your video, enter text or pick a logo, choose the position, and click "Process Video".',
      'faqQ5': 'Where are my files saved?',
      'faqA5': 'Videos and images are saved to your Photo Gallery. Audio files can be found in the "Files" app under "Quick Save".',
      'faqQ6': 'Is it free to use?',
      'faqA6': 'Yes, Quick Save is completely free to use!',
      'faqQ7': 'Supported platforms?',
      'faqA7': 'We support YouTube, Instagram, TikTok, and Facebook.',
    },
    'hi': {
      'appName': 'क्विक सेव',
      'success': 'सफलता',
      'error': 'त्रुटि',
      'ok': 'ठीक है',
      'cancel': 'रद्द करें',
      'loading': 'लोड हो रहा है...',
      'downloadTitle': 'वीडियो और ऑडियो डाउनलोड करें',
      'downloadSubtitle': 'कोई भी लिंक पेस्ट करें और तुरंत सेव करें',
      'pasteUrlHint': 'यहाँ URL पेस्ट करें...',
      'pasteLinkBtn': 'लिंक पेस्ट करें',
      'clearTextBtn': 'साफ़ करें',
      'downloadBtn': 'डाउनलोड',
      'downloaderBtn': 'डाउनलोडर',
      'platforms': 'प्लेटफॉर्म',
      'mediaTools': 'मीडिया टूल्स',
      'seeAll': 'सभी देखें',
      'mediaToolsSubtitle': 'अपने डिवाइस पर पहले से सेव वीडियो या ऑडियो को एडिट करें।',
      'instagram': 'इंस्टाग्राम',
      'facebook': 'फेसबुक',
      'tiktok': 'टिकटॉक',
      'youtube': 'यूट्यूब',
      'other': 'अन्य',
      'removeWatermark': 'मैजिक इरेज़र',
      'removeWatermarkDesc': 'वीडियो और इमेज से अवांछित वस्तुओं को मिटाएं',
      'addWatermark': 'वॉटरमार्क जोड़ें',
      'addWatermarkDesc': 'अपने वीडियो में अपना लोगो या टेक्स्ट जोड़ें',
      'trimVideo': 'वीडियो ट्रिम करें',
      'trimVideoDesc': 'अपने वीडियो के विशिष्ट भागों को काटें',
      'convertFormat': 'फॉर्मेट बदलें',
      'convertFormatDesc': 'वीडियो या ऑडियो फ़ाइल प्रकार बदलें',
      'compress': 'कंप्रेस',
      'compressDesc': 'वीडियो या ऑडियो फ़ाइल का आकार कम करें',
      'removeAudio': 'ऑडियो हटाएं',
      'removeAudioDesc': 'बिना आवाज़ के वीडियो एक्सपोर्ट करें',
      'muteVideo': 'वीडियो म्यूट करें',
      'muteVideoDesc': 'वीडियो से ध्वनि हटाएं',
      'extractMp3': 'MP3 निकालें',
      'extractMp3Desc': 'किसी भी वीडियो फ़ाइल से ऑडियो प्राप्त करें',
      'chooseSource': 'स्रोत चुनें',
      'pickSourceDesc': 'अपनी गैलरी से एक वीडियो चुनें या एक लिंक पेस्ट करें।',
      'uploadFromGallery': 'गैलरी से अपलोड करें',
      'failedToLoadVideo': 'वीडियो लोड करने में विफल',
      'or': 'या',
      'downloading': 'डाउनलोड हो रहा है',
      'processing': 'प्रोसेसिंग',
      'loadFromUrl': 'URL से लोड करें',
      'generatingPreview': 'पूर्वावलोकन तैयार किया जा रहा है...',
      'startTimeLabel': 'शुरू होने का समय (MM:SS)',
      'endTimeLabel': 'समाप्ति का समय (MM:SS)',
      'customTimer': 'कस्टम टाइमर',
      'slider': 'स्लाइडर',
      'trimmingFailed': 'ट्रिमिंग विफल रही',
      'saveTrimmedVideo': 'ट्रिम किया हुआ वीडियो सेव करें',
      'trimmedSavedSuccess': 'ट्रिम किया गया वीडियो गैलरी में सेव किया गया!',
      'pasteLinkFirst': 'पहले लिंक पेस्ट करें',
      'invalidLink': 'अवैध लिंक',
      'couldNotReadLink': 'यह लिंक पढ़ा नहीं जा सका',
      'checkLinkRetry': 'कृपया लिंक जांचें और पुनः प्रयास करें।',
      'copyVideoLinkFrom': 'वीडियो लिंक कॉपी करें',
      'galleryAccessFailed': 'गैलरी एक्सेस विफल',
      'settings': 'सेटिंग्स',
      'preferences': 'प्राथमिकताएं',
      'language': 'भाषा',
      'selectLanguage': 'भाषा चुनें',
      'theme': 'थीम',
      'lightMode': 'लाइट मोड',
      'darkMode': 'डार्क मोड',
      'systemDefault': 'सिस्टम डिफ़ॉल्ट',
      'support': 'सपोर्ट',
      'faq': 'FAQ',
      'faqDesc': 'अक्सर पूछे जाने वाले सवाल',
      'legal': 'कानूनी',
      'terms': 'नियम और शर्तें',
      'termsDesc': 'क्विक सेव का उपयोग करने के नियम',
      'privacy': 'गोपनीयता नीति',
      'privacyDesc': 'हम आपके डेटा को कैसे संभालते हैं',
      'selectFormat': 'फॉर्मेट चुनें',
      'video': 'वीडियो',
      'videoQuality': 'वीडियो की गुणवत्ता',
      'audio': 'ऑडियो',
      'audioQuality': 'ऑडियो की गुणवत्ता',
      'saved': 'सेव हो गया!',
      'viewHistory': 'इतिहास देखें',
      'downloadStarted': 'डाउनलोड शुरू हुआ',
      'downloadFailed': 'डाउनलोड विफल',
      'highQualityMP3': 'उच्च गुणवत्ता · MP3',
      'audioOnly': 'केवल ऑडियो',
      'chooseAQualityFirst': 'पहले गुणवत्ता चुनें',
      'yourFileHasBeenSavedToYourDevice': 'आपकी फ़ाइल आपके डिवाइस में सेव कर दी गई है।',
      'history': 'इतिहास',
      'mp3': 'MP3',
      'clearHistory': 'इतिहास साफ़ करें',
      'noHistory': 'अभी तक कोई डाउनलोड नहीं',
      'tagDownload': 'डाउनलोड किया गया',
      'tagTrim': 'ट्रिम किया गया',
      'tagConvert': 'परिवर्तित',
      'tagEraser': 'मिटाया गया',
      'tagWatermarked': 'वॉटरमार्क किया गया',
      'pleasePasteAValid': 'कृपया एक वैध पेस्ट करें',
      'link': 'लिंक',
      'paste': 'पेस्ट',
      'your': 'अपना',
      'linkHere': 'लिंक यहाँ...',
      'linkBelowToStart': 'शुरू करने के लिए नीचे लिंक।',
      'convertFormatTitle': 'फॉर्मेट बदलें',
      'chooseMediaType': 'मीडिया प्रकार चुनें',
      'selectTargetFormat': 'टारगेट फॉर्मेट चुनें',
      'pickAudioFile': 'ऑडियो फ़ाइल चुनें',
      'pickVideoFile': 'वीडियो फ़ाइल चुनें',
      'convertNow': 'अभी बदलें',
      'converting': 'बदला जा रहा है...',
      'conversionSuccess': 'फ़ाइल सफलतापूर्वक बदल दी गई!',
      'conversionFailed': 'परिवर्तन विफल रहा। कृपया पुनः प्रयास करें।',
      'noFileSelected': 'कृपया पहले एक फ़ाइल चुनें',
      'splashSubtitle': 'डाउनलोड • एडिट • शेयर',
      'languageName': 'हिन्दी',
      'chooseMedia': 'मीडिया चुनें',
      'chooseAudio': 'ऑडियो चुनें',
      'chooseVideo': 'वीडियो चुनें',
      'selectAndContinue': 'चुनें और जारी रखें',
      'position': 'स्थिति',
      'size': 'आकार',
      'magicEraser': 'मैजिक इरेज़र',
      'drawToErase': 'मिटाने के लिए ड्रा करें',
      'simplyDraw': 'बस अपनी उंगली से वॉटरमार्क पर एक बॉक्स बनाएं।',
      'generateVideo': 'वीडियो बनाएं',
      'clearSelection': 'चुनाव साफ़ करें',
      'changeVideo': 'वीडियो बदलें',
      'addBranding': 'ब्रांडिंग जोड़ें',
      'dragBrand': 'अपने ब्रांड को वीडियो पर कहीं भी ड्रैग करें।',
      'typeWatermark': 'वॉटरमार्क टाइप करें...',
      'loadingMedia': 'मीडिया लोड हो रहा है...',
      'watermarkBlur': 'वॉटरमार्क ब्लर',
      'readyToErase': 'मिटाने के लिए तैयार!',
      'eraseSelectedArea': 'चुने हुए क्षेत्र को मिटाएं',
      'openGallery': 'गैलरी खोलें',
      'posBlurBox': 'ब्लर बॉक्स सेट करें',
      'faqQ1': 'वीडियो कैसे डाउनलोड करें?',
      'faqA1': 'किसी भी समर्थित प्लेटफ़ॉर्म से वीडियो लिंक कॉपी करें, उसे होम स्क्रीन पर पेस्ट करें और जारी रखें पर क्लिक करें।',
      'faqQ2': 'मैजिक इरेज़र का उपयोग कैसे करें?',
      'faqA2': 'एक इमेज या वीडियो अपलोड करें, वॉटरमार्क या अवांछित वस्तु पर एक बॉक्स बनाएं, और "चुने हुए क्षेत्र को मिटाएं" पर क्लिक करें।',
      'faqQ3': 'वीडियो को ट्रिम कैसे करें?',
      'faqA3': 'मीडिया टूल्स पर जाएं, ट्रिम वीडियो चुनें, अपना वीडियो अपलोड करें और उस हिस्से को चुनने के लिए स्लाइडर या कस्टम टाइमर का उपयोग करें जिसे आप रखना चाहते हैं।',
      'faqQ4': 'फ़ाइल फॉर्मेट कैसे बदलें?',
      'faqA4': 'मीडिया टूल्स से "फॉर्मेट बदलें" चुनें, ऑडियो या वीडियो में से चुनें, अपनी फ़ाइल चुनें और MP3 या MP4 जैसे टारगेट फॉर्मेट को चुनें।',
      'faqQ8': 'अपने वीडियो में वॉटरमार्क कैसे जोड़ें?',
      'faqA8': 'मीडिया टूल्स > वॉटरमार्क जोड़ें पर जाएं, अपना वीडियो चुनें, टेक्स्ट लिखें या लोगो चुनें, स्थिति चुनें और "वीडियो प्रोसेस करें" पर क्लिक करें।',
      'faqQ5': 'मेरी फाइलें कहां सेव होती हैं?',
      'faqA5': 'वीडियो और इमेज आपकी फोटो गैलरी में सेव किए जाते हैं। ऑडियो फाइलें "फ़ाइलें" ऐप में "क्विक सेव" के तहत मिल सकती हैं।',
      'faqQ6': 'क्या इसका उपयोग मुफ्त है?',
      'faqA6': 'हाँ, क्विक सेव उपयोग करने के लिए पूरी तरह से मुफ्त है!',
      'faqQ7': 'समर्थित प्लेटफार्म?',
      'faqA7': 'हम यूट्यूब, इंस्टाग्राम, टिकटॉक और फेसबुक का समर्थन करते हैं।',
    },
    'pa': {
      'appName': 'ਕੁਵਿੱਕ ਸੇਵ',
      'success': 'ਸਫ਼ਲਤਾ',
      'error': 'ਗਲਤੀ',
      'ok': 'ਠੀਕ ਹੈ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'downloadTitle': 'ਵੀਡੀਓ ਅਤੇ ਆਡੀਓ ਡਾਊਨਲੋਡ ਕਰੋ',
      'downloadSubtitle': 'ਕੋਈ ਵੀ ਲਿੰਕ ਪੇਸਟ ਕਰੋ ਅਤੇ ਤੁਰੰਤ ਸੇਵ ਕਰੋ',
      'pasteUrlHint': 'ਇੱਥੇ URL ਪੇਸਟ ਕਰੋ...',
      'pasteLinkBtn': 'ਲਿੰਕ ਪੇਸਟ ਕਰੋ',
      'clearTextBtn': 'ਸਾਫ਼ ਕਰੋ',
      'downloadBtn': 'ਡਾਊਨਲੋਡ',
      'downloaderBtn': 'ਡਾਊਨਲੋਡਰ',
      'platforms': 'ਪਲੇਟਫਾਰਮ',
      'mediaTools': 'ਮੀਡੀਆ ਟੂਲਸ',
      'seeAll': 'ਸਭ ਦੇਖੋ',
      'mediaToolsSubtitle': 'ਆਪਣੇ ਡਿਵਾਈਸ ਤੇ ਪਹਿਲਾਂ ਤੋਂ ਸੇਵ ਵੀਡੀਓ ਜਾਂ ਆਡੀਓ ਨੂੰ ਐਡਿਟ ਕਰੋ।',
      'instagram': 'ਇੰਸਟਾਗ੍ਰਾਮ',
      'facebook': 'ਫੇਸਬੁੱਕ',
      'tiktok': 'ਟਿੱਕਟੌਕ',
      'youtube': 'ਯੂਟਿਊਬ',
      'other': 'ਹੋਰ',
      'removeWatermark': 'ਮੈਜਿਕ ਇਰੇਜ਼ਰ',
      'removeWatermarkDesc': 'ਵੀਡੀਓ ਅਤੇ ਚਿੱਤਰਾਂ ਤੋਂ ਅਣਚਾਹੇ ਚੀਜ਼ਾਂ ਨੂੰ ਮਿਟਾਓ',
      'addWatermark': 'ਵਾਟਰਮਾਰਕ ਜੋੜੋ',
      'addWatermarkDesc': 'ਆਪਣੇ ਵੀਡੀਓ ਵਿੱਚ ਆਪਣਾ ਲੋਗੋ ਜਾਂ ਟੈਕਸਟ ਜੋੜੋ',
      'trimVideo': 'ਵੀਡੀਓ ਟ੍ਰਿਮ ਕਰੋ',
      'trimVideoDesc': 'ਆਪਣੇ ਵੀਡੀਓ ਦੇ ਖਾਸ ਹਿੱਸੇ ਕੱਟੋ',
      'convertFormat': 'ਫਾਰਮੈਟ ਬਦਲੋ',
      'convertFormatDesc': 'ਵੀਡੀਓ ਜਾਂ ਆਡੀਓ ਫਾਈਲ ਕਿਸਮ ਬਦਲੋ',
      'compress': 'ਕੰਪਰੈੱਸ',
      'compressDesc': 'ਵੀਡੀਓ ਜਾਂ ਆਡੀਓ ਫਾਈਲ ਦਾ ਅਕਾਰ ਘਟਾਓ',
      'removeAudio': 'ਆਡੀਓ ਹਟਾਓ',
      'removeAudioDesc': 'ਬਿਨਾਂ ਆਵਾਜ਼ ਦੇ ਵੀਡੀਓ ਐਕਸਪੋਰਟ ਕਰੋ',
      'muteVideo': 'ਵੀਡੀਓ ਮਿਊਟ ਕਰੋ',
      'muteVideoDesc': 'ਵੀਡੀਓ ਤੋਂ ਆਵਾਜ਼ ਹਟਾਓ',
      'extractMp3': 'MP3 ਕੱਢੋ',
      'extractMp3Desc': 'ਕਿਸੇ ਵੀ ਵੀਡੀਓ ਫਾਈਲ ਤੋਂ ਆਡੀਓ ਪ੍ਰਾਪਤ ਕਰੋ',
      'chooseSource': 'ਸਰੋਤ ਚੁਣੋ',
      'pickSourceDesc': 'ਆਪਣੀ ਗੈਲਰੀ ਵਿੱਚੋਂ ਇੱਕ ਵੀਡੀਓ ਚੁਣੋ ਜਾਂ ਇੱਕ ਲਿੰਕ ਪੇਸਟ ਕਰੋ।',
      'uploadFromGallery': 'ਗੈਲਰੀ ਤੋਂ ਅਪਲੋਡ ਕਰੋ',
      'failedToLoadVideo': 'ਵੀਡੀਓ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ',
      'or': 'ਜਾਂ',
      'downloading': 'ਡਾਊਨਲੋਡ ਹੋ ਰਿਹਾ ਹੈ',
      'processing': 'ਪ੍ਰੋਸੈਸਿੰਗ',
      'loadFromUrl': 'URL ਤੋਂ ਲੋਡ ਕਰੋ',
      'generatingPreview': 'ਪੂਰਵ ਦਰਸ਼ਨ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
      'startTimeLabel': 'ਸ਼ੁਰੂ ਹੋਣ ਦਾ ਸਮਾਂ (MM:SS)',
      'endTimeLabel': 'ਸਮਾਪਤੀ ਦਾ ਸਮਾਂ (MM:SS)',
      'customTimer': 'ਕਸਟਮ ਟਾਈਮਰ',
      'slider': 'ਸਲਾਈਡਰ',
      'trimmingFailed': 'ਟ੍ਰਿਮਿੰਗ ਅਸਫਲ ਰਹੀ',
      'saveTrimmedVideo': 'ਟ੍ਰਿਮ ਕੀਤਾ ਹੋਇਆ ਵੀਡੀਓ ਸੇਵ ਕਰੋ',
      'trimmedSavedSuccess': 'ਟ੍ਰਿਮ ਕੀਤਾ ਵੀਡੀਓ ਗੈਲਰੀ ਵਿੱਚ ਸੇਵ ਹੋ ਗਿਆ!',
      'pasteLinkFirst': 'ਪਹਿਲਾਂ ਲਿੰਕ ਪੇਸਟ ਕਰੋ',
      'invalidLink': 'ਅਵੈਧ ਲਿੰਕ',
      'couldNotReadLink': 'ਇਹ ਲਿੰਕ ਪੜ੍ਹਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ',
      'checkLinkRetry': 'ਕਿਰਪਾ ਕਰਕੇ ਲਿੰਕ ਦੀ ਜਾਂਚ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'copyVideoLinkFrom': 'ਵੀਡੀਓ ਲਿੰਕ ਕਾਪੀ ਕਰੋ',
      'galleryAccessFailed': 'ਗੈਲਰੀ ਤੱਕ ਪਹੁੰਚ ਅਸਫਲ ਰਹੀ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'preferences': 'ਤਰਜੀਹਾਂ',
      'language': 'ਭਾਸ਼ਾ',
      'selectLanguage': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'theme': 'ਥੀਮ',
      'lightMode': 'ਲਾਈਟ ਮੋਡ',
      'darkMode': 'ਡਾਰਕ ਮੋਡ',
      'systemDefault': 'ਸਿਸਟਮ ਡਿਫੌਲਟ',
      'support': 'ਸਹਾਇਤਾ',
      'faq': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
      'faqDesc': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
      'legal': 'ਕਾਨੂੰਨੀ',
      'terms': 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ',
      'termsDesc': 'ਕੁਵਿੱਕ ਸੇਵ ਦੀ ਵਰਤੋਂ ਦੇ ਨਿਯਮ',
      'privacy': 'ਪਰਾਈਵੇਸੀ ਪਾਲਿਸੀ',
      'privacyDesc': 'ਅਸੀਂ ਤੁਹਾਡੇ ਡੇਟਾ ਨੂੰ ਕਿਵੇਂ ਸੰਭਾਲਦੇ ਹਾਂ',
      'selectFormat': 'ਫਾਰਮੈਟ ਚੁਣੋ',
      'video': 'ਵੀਡੀਓ',
      'videoQuality': 'ਵੀਡੀਓ ਕੁਆਲਿਟੀ',
      'audio': 'ਆਡੀਓ',
      'audioQuality': 'ਆਡੀਓ ਕੁਆਲਿਟੀ',
      'saved': 'ਸੇਵ ਹੋ ਗਿਆ!',
      'viewHistory': 'ਹਿਸਟਰੀ ਦੇਖੋ',
      'downloadStarted': 'ਡਾਊਨਲੋਡ ਸ਼ੁਰੂ ਹੋਇਆ',
      'downloadFailed': 'ਡਾਊਨਲੋਡ ਅਸਫਲ',
      'highQualityMP3': 'ਹਾਈ ਕੁਆਲਿਟੀ · MP3',
      'audioOnly': 'ਸਿਰਫ਼ ਆਡੀਓ',
      'chooseAQualityFirst': 'ਪਹਿਲਾਂ ਕੁਆਲਿਟੀ ਚੁਣੋ',
      'yourFileHasBeenSavedToYourDevice': 'ਤੁਹਾਡੀ ਫਾਈਲ ਤੁਹਾਡੇ ਡਿਵਾਈਸ ਤੇ ਸੇਵ ਹੋ ਗਈ ਹੈ।',
      'history': 'ਹਿਸਟਰੀ',
      'mp3': 'MP3',
      'clearHistory': 'ਹਿਸਟਰੀ ਸਾਫ਼ ਕਰੋ',
      'noHistory': 'ਅਜੇ ਤੱਕ ਕੋਈ ਡਾਊਨਲੋਡ ਨਹੀਂ',
      'tagDownload': 'ਡਾਊਨਲੋਡ ਕੀਤਾ',
      'tagTrim': 'ਟ੍ਰਿਮ ਕੀਤਾ',
      'tagConvert': 'ਬਦਲਿਆ ਗਿਆ',
      'tagEraser': 'ਮਿਟਾਇਆ ਗਿਆ',
      'tagWatermarked': 'ਵਾਟਰਮਾਰਕ ਲਗਾਇਆ',
      'pleasePasteAValid': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਪੇਸਟ ਕਰੋ',
      'link': 'ਲਿੰਕ',
      'paste': 'ਪੇਸਟ',
      'your': 'ਤੁਹਾਡਾ',
      'linkHere': 'ਲਿੰਕ ਇੱਥੇ...',
      'linkBelowToStart': 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਹੇਠਾਂ ਲਿੰਕ।',
      'convertFormatTitle': 'ਫਾਰਮੈਟ ਬਦਲੋ',
      'chooseMediaType': 'ਮੀਡੀਆ ਕਿਸਮ ਚੁਣੋ',
      'selectTargetFormat': 'ਟਾਰਗੇਟ ਫਾਰਮੈਟ ਚੁਣੋ',
      'pickAudioFile': 'ਆਡੀਓ ਫਾਈਲ ਚੁਣੋ',
      'pickVideoFile': 'ਵੀਡੀਓ ਫਾਈਲ ਚੁਣੋ',
      'convertNow': 'ਹੁਣੇ ਬਦਲੋ',
      'converting': 'ਬਦਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      'conversionSuccess': 'ਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਬਦਲੀ ਗਈ!',
      'conversionFailed': 'ਪਰਿਵਰਤਨ ਅਸਫਲ ਰਿਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'noFileSelected': 'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਇੱਕ ਫਾਈਲ ਚੁਣੋ',
      'splashSubtitle': 'ਡਾਊਨਲੋਡ • ਐਡਿਟ • ਸ਼ੇਅਰ',
      'languageName': 'ਪੰਜਾਬੀ',
      'chooseMedia': 'ਮੀਡੀਆ ਚੁਣੋ',
      'chooseAudio': 'ਆਡੀਓ ਚੁਣੋ',
      'chooseVideo': 'ਵੀਡੀਓ ਚੁਣੋ',
      'selectAndContinue': 'ਚੁਣੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ',
      'position': 'ਸਥਿਤੀ',
      'size': 'ਅਕਾਰ',
      'magicEraser': 'ਮੈਜਿਕ ਇਰੇਜ਼ਰ',
      'drawToErase': 'ਮਿਟਾਉਣ ਲਈ ਡਰਾਅ ਕਰੋ',
      'simplyDraw': 'ਬੱਸ ਆਪਣੀ ਉਂਗਲ ਨਾਲ ਵਾਟਰਮਾਰਕ ਤੇ ਇੱਕ ਬਾਕਸ ਬਣਾਓ।',
      'generateVideo': 'ਵੀਡੀਓ ਬਣਾਓ',
      'clearSelection': 'ਚੋਣ ਸਾਫ਼ ਕਰੋ',
      'changeVideo': 'ਵੀਡੀਓ ਬਦਲੋ',
      'addBranding': 'ਬ੍ਰਾਂਡਿੰਗ ਜੋੜੋ',
      'dragBrand': 'ਆਪਣੇ ਬ੍ਰਾਂਡ ਨੂੰ ਵੀਡੀਓ ਤੇ ਕਿਤੇ ਵੀ ਡਰੈਗ ਕਰੋ।',
      'typeWatermark': 'ਵਾਟਰਮਾਰਕ ਟਾਈਪ ਕਰੋ...',
      'loadingMedia': 'ਮੀਡੀਆ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'watermarkBlur': 'ਵਾਟਰਮਾਰਕ ਬਲਰ',
      'readyToErase': 'ਮਿਟਾਉਣ ਲਈ ਤਿਆਰ!',
      'eraseSelectedArea': 'ਚੋਣ ਸਾਫ਼ ਕਰੋ',
      'openGallery': 'ਗੈਲਰੀ ਖੋਲ੍ਹੋ',
      'posBlurBox': 'ਬਲਰ ਬਾਕਸ ਸੈੱਟ ਕਰੋ',
      'faqQ1': 'ਵੀਡੀਓ ਕਿਵੇਂ ਡਾਊਨਲੋਡ ਕਰੀਏ?',
      'faqA1': 'ਕਿਸੇ ਵੀ ਸਮਰਥਿਤ ਪਲੇਟਫਾਰਮ ਤੋਂ ਵੀਡੀਓ ਲਿੰਕ ਕਾਪੀ ਕਰੋ, ਇਸਨੂੰ ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਪੇਸਟ ਕਰੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ ਤੇ ਕਲਿਕ ਕਰੋ।',
      'faqQ2': 'ਮੈਜਿਕ ਇਰੇਜ਼ਰ ਦੀ ਵਰਤੋਂ ਕਿਵੇਂ ਕਰੀਏ?',
      'faqA2': 'ਇੱਕ ਚਿੱਤਰ ਜਾਂ ਵੀਡੀਓ ਅਪਲੋਡ ਕਰੋ, ਵਾਟਰਮਾਰਕ ਜਾਂ ਅਣਚਾਹੇ ਹਿੱਸੇ ਤੇ ਇੱਕ ਬਾਕਸ ਬਣਾਓ, ਅਤੇ "ਚੁਣੇ ਹੋਏ ਹਿੱਸੇ ਨੂੰ ਮਿਟਾਓ" ਤੇ ਕਲਿਕ ਕਰੋ।',
      'faqQ3': 'ਵੀਡੀਓ ਨੂੰ ਟ੍ਰਿਮ ਕਿਵੇਂ ਕਰੀਏ?',
      'faqA3': 'ਮੀਡੀਆ ਟੂਲਸ ਤੇ ਜਾਓ, ਟ੍ਰਿਮ ਵੀਡੀਓ ਚੁਣੋ, ਆਪਣਾ ਵੀਡੀਓ ਅਪਲੋਡ ਕਰੋ ਅਤੇ ਉਹ ਹਿੱਸਾ ਚੁਣਨ ਲਈ ਸਲਾਈਡਰ ਜਾਂ ਕਸਟਮ ਟਾਈਮਰ ਦੀ ਵਰਤੋਂ ਕਰੋ ਜਿਸਨੂੰ ਤੁਸੀਂ ਰੱਖਣਾ ਚਾਹੁੰਦੇ ਹੋ।',
      'faqQ4': 'ਫਾਈਲ ਫਾਰਮੈਟ ਕਿਵੇਂ ਬਦਲੀਏ?',
      'faqA4': 'ਮੀਡੀਆ ਟੂਲਸ ਤੋਂ "ਫਾਰਮੈਟ ਬਦਲੋ" ਚੁਣੋ, ਆਡੀਓ ਜਾਂ ਵੀਡੀਓ ਵਿੱਚੋਂ ਚੁਣੋ, ਆਪਣੀ ਫਾਈਲ ਚੁਣੋ ਅਤੇ MP3 ਜਾਂ MP4 ਵਰਗੇ ਟਾਰਗੇਟ ਫਾਰਮੈਟ ਨੂੰ ਚੁਣੋ।',
      'faqQ8': 'ਆਪਣੇ ਵੀਡੀਓ ਵਿੱਚ ਵਾਟਰਮਾਰਕ ਕਿਵੇਂ ਜੋੜੀਏ?',
      'faqA8': 'ਮੀਡੀਆ ਟੂਲਸ > ਵਾਟਰਮਾਰਕ ਜੋੜੋ ਤੇ ਜਾਓ, ਆਪਣਾ ਵੀਡੀਓ ਚੁਣੋ, ਟੈਕਸਟ ਲਿਖੋ ਜਾਂ ਲੋਗੋ ਚੁਣੋ, ਸਥਿਤੀ ਚੁਣੋ ਅਤੇ "ਵੀਡੀਓ ਪ੍ਰੋਸੈਸ ਕਰੋ" ਤੇ ਕਲਿਕ ਕਰੋ।',
      'faqQ5': 'ਮੇਰੀਆਂ ਫਾਈਲਾਂ ਕਿੱਥੇ ਸੇਵ ਹੁੰਦੀਆਂ ਹਨ?',
      'faqA5': 'ਵੀਡੀਓ ਅਤੇ ਚਿੱਤਰ ਤੁਹਾਡੀ ਫੋਟੋ ਗੈਲਰੀ ਵਿੱਚ ਸੇਵ ਕੀਤੇ ਜਾਂਦੇ ਹਨ। ਆਡੀਓ ਫਾਈਲਾਂ "ਫਾਈਲਾਂ" ਐਪ ਵਿੱਚ "ਕੁਵਿੱਕ ਸੇਵ" ਦੇ ਅਧੀਨ ਮਿਲ ਸਕਦੀਆਂ ਹਨ।',
      'faqQ6': 'ਕੀ ਇਹ ਵਰਤਣ ਲਈ ਮੁਫ਼ਤ ਹੈ?',
      'faqA6': 'ਹਾਂ, ਕੁਵਿੱਕ ਸੇਵ ਵਰਤਣ ਲਈ ਪੂਰੀ ਤਰ੍ਹਾਂ ਮੁਫ਼ਤ ਹੈ!',
      'faqQ7': 'ਸਮਰਥਿਤ ਪਲੇਟਫਾਰਮ?',
      'faqA7': 'ਅਸੀਂ ਯੂਟਿਊਬ, ਇੰਸਟਾਗ੍ਰਾਮ, ਟਿੱਕਟੌਕ ਅਤੇ ਫੇਸਬੁੱਕ ਦਾ ਸਮਰਥਨ ਕਰਦੇ ਹਾਂ।',
    }
  };
}
